/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated.index'
import { Route as ApiTwilioSettingsRouteImport } from './routes/api/twilio-settings'
import { Route as ApiSettingsRouteImport } from './routes/api/settings'
import { Route as ApiMessagingProviderRouteImport } from './routes/api/messaging-provider'
import { Route as ApiConnectionsRouteImport } from './routes/api/connections'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated.settings'
import { Route as AuthenticatedLeadsRouteImport } from './routes/_authenticated.leads'
import { Route as AuthenticatedKnowledgeRouteImport } from './routes/_authenticated.knowledge'
import { Route as AuthenticatedInboxRouteImport } from './routes/_authenticated.inbox'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated.dashboard'
import { Route as AuthenticatedConnectionsRouteImport } from './routes/_authenticated.connections'
import { Route as AuthenticatedCampaignsRouteImport } from './routes/_authenticated.campaigns'
import { Route as AuthenticatedLeadsIndexRouteImport } from './routes/_authenticated.leads.index'
import { Route as AuthenticatedCampaignsIndexRouteImport } from './routes/_authenticated.campaigns.index'
import { Route as AuthenticatedSettingsWhatsappRouteImport } from './routes/_authenticated.settings.whatsapp'
import { Route as AuthenticatedSettingsWebhooksRouteImport } from './routes/_authenticated.settings.webhooks'
import { Route as AuthenticatedSettingsUsersRouteImport } from './routes/_authenticated.settings.users'
import { Route as AuthenticatedSettingsTwilioRouteImport } from './routes/_authenticated.settings.twilio'
import { Route as AuthenticatedSettingsKnowledgeRouteImport } from './routes/_authenticated.settings.knowledge'
import { Route as AuthenticatedSettingsEvolutionRouteImport } from './routes/_authenticated.settings.evolution'
import { Route as AuthenticatedSettingsConnectionsRouteImport } from './routes/_authenticated.settings.connections'
import { Route as AuthenticatedSettingsBotRouteImport } from './routes/_authenticated.settings.bot'
import { Route as AuthenticatedSettingsAiProvidersRouteImport } from './routes/_authenticated.settings.ai-providers'
import { Route as AuthenticatedLeadsIdRouteImport } from './routes/_authenticated.leads.$id'
import { Route as AuthenticatedCampaignsIdRouteImport } from './routes/_authenticated.campaigns.$id'
import { Route as ApiPublicWebhooksEvolutionRouteImport } from './routes/api/public/webhooks/evolution'
import { Route as ApiPublicCampaignsTickRouteImport } from './routes/api/public/campaigns/tick'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const ApiTwilioSettingsRoute = ApiTwilioSettingsRouteImport.update({
  id: '/api/twilio-settings',
  path: '/api/twilio-settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSettingsRoute = ApiSettingsRouteImport.update({
  id: '/api/settings',
  path: '/api/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMessagingProviderRoute = ApiMessagingProviderRouteImport.update({
  id: '/api/messaging-provider',
  path: '/api/messaging-provider',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiConnectionsRoute = ApiConnectionsRouteImport.update({
  id: '/api/connections',
  path: '/api/connections',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedLeadsRoute = AuthenticatedLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedKnowledgeRoute = AuthenticatedKnowledgeRouteImport.update({
  id: '/knowledge',
  path: '/knowledge',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedInboxRoute = AuthenticatedInboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedConnectionsRoute =
  AuthenticatedConnectionsRouteImport.update({
    id: '/connections',
    path: '/connections',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCampaignsRoute = AuthenticatedCampaignsRouteImport.update({
  id: '/campaigns',
  path: '/campaigns',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedLeadsIndexRoute = AuthenticatedLeadsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedLeadsRoute,
} as any)
const AuthenticatedCampaignsIndexRoute =
  AuthenticatedCampaignsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedCampaignsRoute,
  } as any)
const AuthenticatedSettingsWhatsappRoute =
  AuthenticatedSettingsWhatsappRouteImport.update({
    id: '/whatsapp',
    path: '/whatsapp',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedSettingsWebhooksRoute =
  AuthenticatedSettingsWebhooksRouteImport.update({
    id: '/webhooks',
    path: '/webhooks',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedSettingsUsersRoute =
  AuthenticatedSettingsUsersRouteImport.update({
    id: '/users',
    path: '/users',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedSettingsTwilioRoute =
  AuthenticatedSettingsTwilioRouteImport.update({
    id: '/twilio',
    path: '/twilio',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedSettingsKnowledgeRoute =
  AuthenticatedSettingsKnowledgeRouteImport.update({
    id: '/knowledge',
    path: '/knowledge',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedSettingsEvolutionRoute =
  AuthenticatedSettingsEvolutionRouteImport.update({
    id: '/evolution',
    path: '/evolution',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedSettingsConnectionsRoute =
  AuthenticatedSettingsConnectionsRouteImport.update({
    id: '/connections',
    path: '/connections',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedSettingsBotRoute =
  AuthenticatedSettingsBotRouteImport.update({
    id: '/bot',
    path: '/bot',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedSettingsAiProvidersRoute =
  AuthenticatedSettingsAiProvidersRouteImport.update({
    id: '/ai-providers',
    path: '/ai-providers',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedLeadsIdRoute = AuthenticatedLeadsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedLeadsRoute,
} as any)
const AuthenticatedCampaignsIdRoute =
  AuthenticatedCampaignsIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedCampaignsRoute,
  } as any)
const ApiPublicWebhooksEvolutionRoute =
  ApiPublicWebhooksEvolutionRouteImport.update({
    id: '/api/public/webhooks/evolution',
    path: '/api/public/webhooks/evolution',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicCampaignsTickRoute = ApiPublicCampaignsTickRouteImport.update({
  id: '/api/public/campaigns/tick',
  path: '/api/public/campaigns/tick',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/login': typeof LoginRoute
  '/campaigns': typeof AuthenticatedCampaignsRouteWithChildren
  '/connections': typeof AuthenticatedConnectionsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/inbox': typeof AuthenticatedInboxRoute
  '/knowledge': typeof AuthenticatedKnowledgeRoute
  '/leads': typeof AuthenticatedLeadsRouteWithChildren
  '/settings': typeof AuthenticatedSettingsRouteWithChildren
  '/api/connections': typeof ApiConnectionsRoute
  '/api/messaging-provider': typeof ApiMessagingProviderRoute
  '/api/settings': typeof ApiSettingsRoute
  '/api/twilio-settings': typeof ApiTwilioSettingsRoute
  '/campaigns/$id': typeof AuthenticatedCampaignsIdRoute
  '/leads/$id': typeof AuthenticatedLeadsIdRoute
  '/settings/ai-providers': typeof AuthenticatedSettingsAiProvidersRoute
  '/settings/bot': typeof AuthenticatedSettingsBotRoute
  '/settings/connections': typeof AuthenticatedSettingsConnectionsRoute
  '/settings/evolution': typeof AuthenticatedSettingsEvolutionRoute
  '/settings/knowledge': typeof AuthenticatedSettingsKnowledgeRoute
  '/settings/twilio': typeof AuthenticatedSettingsTwilioRoute
  '/settings/users': typeof AuthenticatedSettingsUsersRoute
  '/settings/webhooks': typeof AuthenticatedSettingsWebhooksRoute
  '/settings/whatsapp': typeof AuthenticatedSettingsWhatsappRoute
  '/campaigns/': typeof AuthenticatedCampaignsIndexRoute
  '/leads/': typeof AuthenticatedLeadsIndexRoute
  '/api/public/campaigns/tick': typeof ApiPublicCampaignsTickRoute
  '/api/public/webhooks/evolution': typeof ApiPublicWebhooksEvolutionRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/connections': typeof AuthenticatedConnectionsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/inbox': typeof AuthenticatedInboxRoute
  '/knowledge': typeof AuthenticatedKnowledgeRoute
  '/settings': typeof AuthenticatedSettingsRouteWithChildren
  '/api/connections': typeof ApiConnectionsRoute
  '/api/messaging-provider': typeof ApiMessagingProviderRoute
  '/api/settings': typeof ApiSettingsRoute
  '/api/twilio-settings': typeof ApiTwilioSettingsRoute
  '/': typeof AuthenticatedIndexRoute
  '/campaigns/$id': typeof AuthenticatedCampaignsIdRoute
  '/leads/$id': typeof AuthenticatedLeadsIdRoute
  '/settings/ai-providers': typeof AuthenticatedSettingsAiProvidersRoute
  '/settings/bot': typeof AuthenticatedSettingsBotRoute
  '/settings/connections': typeof AuthenticatedSettingsConnectionsRoute
  '/settings/evolution': typeof AuthenticatedSettingsEvolutionRoute
  '/settings/knowledge': typeof AuthenticatedSettingsKnowledgeRoute
  '/settings/twilio': typeof AuthenticatedSettingsTwilioRoute
  '/settings/users': typeof AuthenticatedSettingsUsersRoute
  '/settings/webhooks': typeof AuthenticatedSettingsWebhooksRoute
  '/settings/whatsapp': typeof AuthenticatedSettingsWhatsappRoute
  '/campaigns': typeof AuthenticatedCampaignsIndexRoute
  '/leads': typeof AuthenticatedLeadsIndexRoute
  '/api/public/campaigns/tick': typeof ApiPublicCampaignsTickRoute
  '/api/public/webhooks/evolution': typeof ApiPublicWebhooksEvolutionRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/campaigns': typeof AuthenticatedCampaignsRouteWithChildren
  '/_authenticated/connections': typeof AuthenticatedConnectionsRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/inbox': typeof AuthenticatedInboxRoute
  '/_authenticated/knowledge': typeof AuthenticatedKnowledgeRoute
  '/_authenticated/leads': typeof AuthenticatedLeadsRouteWithChildren
  '/_authenticated/settings': typeof AuthenticatedSettingsRouteWithChildren
  '/api/connections': typeof ApiConnectionsRoute
  '/api/messaging-provider': typeof ApiMessagingProviderRoute
  '/api/settings': typeof ApiSettingsRoute
  '/api/twilio-settings': typeof ApiTwilioSettingsRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/campaigns/$id': typeof AuthenticatedCampaignsIdRoute
  '/_authenticated/leads/$id': typeof AuthenticatedLeadsIdRoute
  '/_authenticated/settings/ai-providers': typeof AuthenticatedSettingsAiProvidersRoute
  '/_authenticated/settings/bot': typeof AuthenticatedSettingsBotRoute
  '/_authenticated/settings/connections': typeof AuthenticatedSettingsConnectionsRoute
  '/_authenticated/settings/evolution': typeof AuthenticatedSettingsEvolutionRoute
  '/_authenticated/settings/knowledge': typeof AuthenticatedSettingsKnowledgeRoute
  '/_authenticated/settings/twilio': typeof AuthenticatedSettingsTwilioRoute
  '/_authenticated/settings/users': typeof AuthenticatedSettingsUsersRoute
  '/_authenticated/settings/webhooks': typeof AuthenticatedSettingsWebhooksRoute
  '/_authenticated/settings/whatsapp': typeof AuthenticatedSettingsWhatsappRoute
  '/_authenticated/campaigns/': typeof AuthenticatedCampaignsIndexRoute
  '/_authenticated/leads/': typeof AuthenticatedLeadsIndexRoute
  '/api/public/campaigns/tick': typeof ApiPublicCampaignsTickRoute
  '/api/public/webhooks/evolution': typeof ApiPublicWebhooksEvolutionRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/campaigns'
    | '/connections'
    | '/dashboard'
    | '/inbox'
    | '/knowledge'
    | '/leads'
    | '/settings'
    | '/api/connections'
    | '/api/messaging-provider'
    | '/api/settings'
    | '/api/twilio-settings'
    | '/campaigns/$id'
    | '/leads/$id'
    | '/settings/ai-providers'
    | '/settings/bot'
    | '/settings/connections'
    | '/settings/evolution'
    | '/settings/knowledge'
    | '/settings/twilio'
    | '/settings/users'
    | '/settings/webhooks'
    | '/settings/whatsapp'
    | '/campaigns/'
    | '/leads/'
    | '/api/public/campaigns/tick'
    | '/api/public/webhooks/evolution'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/connections'
    | '/dashboard'
    | '/inbox'
    | '/knowledge'
    | '/settings'
    | '/api/connections'
    | '/api/messaging-provider'
    | '/api/settings'
    | '/api/twilio-settings'
    | '/'
    | '/campaigns/$id'
    | '/leads/$id'
    | '/settings/ai-providers'
    | '/settings/bot'
    | '/settings/connections'
    | '/settings/evolution'
    | '/settings/knowledge'
    | '/settings/twilio'
    | '/settings/users'
    | '/settings/webhooks'
    | '/settings/whatsapp'
    | '/campaigns'
    | '/leads'
    | '/api/public/campaigns/tick'
    | '/api/public/webhooks/evolution'
  id:
    | '__root__'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/campaigns'
    | '/_authenticated/connections'
    | '/_authenticated/dashboard'
    | '/_authenticated/inbox'
    | '/_authenticated/knowledge'
    | '/_authenticated/leads'
    | '/_authenticated/settings'
    | '/api/connections'
    | '/api/messaging-provider'
    | '/api/settings'
    | '/api/twilio-settings'
    | '/_authenticated/'
    | '/_authenticated/campaigns/$id'
    | '/_authenticated/leads/$id'
    | '/_authenticated/settings/ai-providers'
    | '/_authenticated/settings/bot'
    | '/_authenticated/settings/connections'
    | '/_authenticated/settings/evolution'
    | '/_authenticated/settings/knowledge'
    | '/_authenticated/settings/twilio'
    | '/_authenticated/settings/users'
    | '/_authenticated/settings/webhooks'
    | '/_authenticated/settings/whatsapp'
    | '/_authenticated/campaigns/'
    | '/_authenticated/leads/'
    | '/api/public/campaigns/tick'
    | '/api/public/webhooks/evolution'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  ApiConnectionsRoute: typeof ApiConnectionsRoute
  ApiMessagingProviderRoute: typeof ApiMessagingProviderRoute
  ApiSettingsRoute: typeof ApiSettingsRoute
  ApiTwilioSettingsRoute: typeof ApiTwilioSettingsRoute
  ApiPublicCampaignsTickRoute: typeof ApiPublicCampaignsTickRoute
  ApiPublicWebhooksEvolutionRoute: typeof ApiPublicWebhooksEvolutionRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/twilio-settings': {
      id: '/api/twilio-settings'
      path: '/api/twilio-settings'
      fullPath: '/api/twilio-settings'
      preLoaderRoute: typeof ApiTwilioSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/settings': {
      id: '/api/settings'
      path: '/api/settings'
      fullPath: '/api/settings'
      preLoaderRoute: typeof ApiSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/messaging-provider': {
      id: '/api/messaging-provider'
      path: '/api/messaging-provider'
      fullPath: '/api/messaging-provider'
      preLoaderRoute: typeof ApiMessagingProviderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/connections': {
      id: '/api/connections'
      path: '/api/connections'
      fullPath: '/api/connections'
      preLoaderRoute: typeof ApiConnectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/leads': {
      id: '/_authenticated/leads'
      path: '/leads'
      fullPath: '/leads'
      preLoaderRoute: typeof AuthenticatedLeadsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/knowledge': {
      id: '/_authenticated/knowledge'
      path: '/knowledge'
      fullPath: '/knowledge'
      preLoaderRoute: typeof AuthenticatedKnowledgeRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/inbox': {
      id: '/_authenticated/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof AuthenticatedInboxRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/connections': {
      id: '/_authenticated/connections'
      path: '/connections'
      fullPath: '/connections'
      preLoaderRoute: typeof AuthenticatedConnectionsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/campaigns': {
      id: '/_authenticated/campaigns'
      path: '/campaigns'
      fullPath: '/campaigns'
      preLoaderRoute: typeof AuthenticatedCampaignsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/leads/': {
      id: '/_authenticated/leads/'
      path: '/'
      fullPath: '/leads/'
      preLoaderRoute: typeof AuthenticatedLeadsIndexRouteImport
      parentRoute: typeof AuthenticatedLeadsRoute
    }
    '/_authenticated/campaigns/': {
      id: '/_authenticated/campaigns/'
      path: '/'
      fullPath: '/campaigns/'
      preLoaderRoute: typeof AuthenticatedCampaignsIndexRouteImport
      parentRoute: typeof AuthenticatedCampaignsRoute
    }
    '/_authenticated/settings/whatsapp': {
      id: '/_authenticated/settings/whatsapp'
      path: '/whatsapp'
      fullPath: '/settings/whatsapp'
      preLoaderRoute: typeof AuthenticatedSettingsWhatsappRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/settings/webhooks': {
      id: '/_authenticated/settings/webhooks'
      path: '/webhooks'
      fullPath: '/settings/webhooks'
      preLoaderRoute: typeof AuthenticatedSettingsWebhooksRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/settings/users': {
      id: '/_authenticated/settings/users'
      path: '/users'
      fullPath: '/settings/users'
      preLoaderRoute: typeof AuthenticatedSettingsUsersRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/settings/twilio': {
      id: '/_authenticated/settings/twilio'
      path: '/twilio'
      fullPath: '/settings/twilio'
      preLoaderRoute: typeof AuthenticatedSettingsTwilioRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/settings/knowledge': {
      id: '/_authenticated/settings/knowledge'
      path: '/knowledge'
      fullPath: '/settings/knowledge'
      preLoaderRoute: typeof AuthenticatedSettingsKnowledgeRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/settings/evolution': {
      id: '/_authenticated/settings/evolution'
      path: '/evolution'
      fullPath: '/settings/evolution'
      preLoaderRoute: typeof AuthenticatedSettingsEvolutionRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/settings/connections': {
      id: '/_authenticated/settings/connections'
      path: '/connections'
      fullPath: '/settings/connections'
      preLoaderRoute: typeof AuthenticatedSettingsConnectionsRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/settings/bot': {
      id: '/_authenticated/settings/bot'
      path: '/bot'
      fullPath: '/settings/bot'
      preLoaderRoute: typeof AuthenticatedSettingsBotRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/settings/ai-providers': {
      id: '/_authenticated/settings/ai-providers'
      path: '/ai-providers'
      fullPath: '/settings/ai-providers'
      preLoaderRoute: typeof AuthenticatedSettingsAiProvidersRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/leads/$id': {
      id: '/_authenticated/leads/$id'
      path: '/$id'
      fullPath: '/leads/$id'
      preLoaderRoute: typeof AuthenticatedLeadsIdRouteImport
      parentRoute: typeof AuthenticatedLeadsRoute
    }
    '/_authenticated/campaigns/$id': {
      id: '/_authenticated/campaigns/$id'
      path: '/$id'
      fullPath: '/campaigns/$id'
      preLoaderRoute: typeof AuthenticatedCampaignsIdRouteImport
      parentRoute: typeof AuthenticatedCampaignsRoute
    }
    '/api/public/webhooks/evolution': {
      id: '/api/public/webhooks/evolution'
      path: '/api/public/webhooks/evolution'
      fullPath: '/api/public/webhooks/evolution'
      preLoaderRoute: typeof ApiPublicWebhooksEvolutionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/campaigns/tick': {
      id: '/api/public/campaigns/tick'
      path: '/api/public/campaigns/tick'
      fullPath: '/api/public/campaigns/tick'
      preLoaderRoute: typeof ApiPublicCampaignsTickRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedCampaignsRouteChildren {
  AuthenticatedCampaignsIdRoute: typeof AuthenticatedCampaignsIdRoute
  AuthenticatedCampaignsIndexRoute: typeof AuthenticatedCampaignsIndexRoute
}

const AuthenticatedCampaignsRouteChildren: AuthenticatedCampaignsRouteChildren =
  {
    AuthenticatedCampaignsIdRoute: AuthenticatedCampaignsIdRoute,
    AuthenticatedCampaignsIndexRoute: AuthenticatedCampaignsIndexRoute,
  }

const AuthenticatedCampaignsRouteWithChildren =
  AuthenticatedCampaignsRoute._addFileChildren(
    AuthenticatedCampaignsRouteChildren,
  )

interface AuthenticatedLeadsRouteChildren {
  AuthenticatedLeadsIdRoute: typeof AuthenticatedLeadsIdRoute
  AuthenticatedLeadsIndexRoute: typeof AuthenticatedLeadsIndexRoute
}

const AuthenticatedLeadsRouteChildren: AuthenticatedLeadsRouteChildren = {
  AuthenticatedLeadsIdRoute: AuthenticatedLeadsIdRoute,
  AuthenticatedLeadsIndexRoute: AuthenticatedLeadsIndexRoute,
}

const AuthenticatedLeadsRouteWithChildren =
  AuthenticatedLeadsRoute._addFileChildren(AuthenticatedLeadsRouteChildren)

interface AuthenticatedSettingsRouteChildren {
  AuthenticatedSettingsAiProvidersRoute: typeof AuthenticatedSettingsAiProvidersRoute
  AuthenticatedSettingsBotRoute: typeof AuthenticatedSettingsBotRoute
  AuthenticatedSettingsConnectionsRoute: typeof AuthenticatedSettingsConnectionsRoute
  AuthenticatedSettingsEvolutionRoute: typeof AuthenticatedSettingsEvolutionRoute
  AuthenticatedSettingsKnowledgeRoute: typeof AuthenticatedSettingsKnowledgeRoute
  AuthenticatedSettingsTwilioRoute: typeof AuthenticatedSettingsTwilioRoute
  AuthenticatedSettingsUsersRoute: typeof AuthenticatedSettingsUsersRoute
  AuthenticatedSettingsWebhooksRoute: typeof AuthenticatedSettingsWebhooksRoute
  AuthenticatedSettingsWhatsappRoute: typeof AuthenticatedSettingsWhatsappRoute
}

const AuthenticatedSettingsRouteChildren: AuthenticatedSettingsRouteChildren = {
  AuthenticatedSettingsAiProvidersRoute: AuthenticatedSettingsAiProvidersRoute,
  AuthenticatedSettingsBotRoute: AuthenticatedSettingsBotRoute,
  AuthenticatedSettingsConnectionsRoute: AuthenticatedSettingsConnectionsRoute,
  AuthenticatedSettingsEvolutionRoute: AuthenticatedSettingsEvolutionRoute,
  AuthenticatedSettingsKnowledgeRoute: AuthenticatedSettingsKnowledgeRoute,
  AuthenticatedSettingsTwilioRoute: AuthenticatedSettingsTwilioRoute,
  AuthenticatedSettingsUsersRoute: AuthenticatedSettingsUsersRoute,
  AuthenticatedSettingsWebhooksRoute: AuthenticatedSettingsWebhooksRoute,
  AuthenticatedSettingsWhatsappRoute: AuthenticatedSettingsWhatsappRoute,
}

const AuthenticatedSettingsRouteWithChildren =
  AuthenticatedSettingsRoute._addFileChildren(
    AuthenticatedSettingsRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedCampaignsRoute: typeof AuthenticatedCampaignsRouteWithChildren
  AuthenticatedConnectionsRoute: typeof AuthenticatedConnectionsRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedInboxRoute: typeof AuthenticatedInboxRoute
  AuthenticatedKnowledgeRoute: typeof AuthenticatedKnowledgeRoute
  AuthenticatedLeadsRoute: typeof AuthenticatedLeadsRouteWithChildren
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRouteWithChildren
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedCampaignsRoute: AuthenticatedCampaignsRouteWithChildren,
  AuthenticatedConnectionsRoute: AuthenticatedConnectionsRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedInboxRoute: AuthenticatedInboxRoute,
  AuthenticatedKnowledgeRoute: AuthenticatedKnowledgeRoute,
  AuthenticatedLeadsRoute: AuthenticatedLeadsRouteWithChildren,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRouteWithChildren,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  ApiConnectionsRoute: ApiConnectionsRoute,
  ApiMessagingProviderRoute: ApiMessagingProviderRoute,
  ApiSettingsRoute: ApiSettingsRoute,
  ApiTwilioSettingsRoute: ApiTwilioSettingsRoute,
  ApiPublicCampaignsTickRoute: ApiPublicCampaignsTickRoute,
  ApiPublicWebhooksEvolutionRoute: ApiPublicWebhooksEvolutionRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
